---
title: "Best Practice Research"
author: "Jenna Reps, Peter R. Rijnbeek"
date: '`r Sys.Date()`'
header-includes:
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \fancyhead{}
    - \fancyhead[CO,CE]{Installation Guide}
    - \fancyfoot[CO,CE]{PatientLevelPrediction Package Version `r    utils::packageVersion("PatientLevelPrediction")`}
    - \fancyfoot[LE,RO]{\thepage}
    - \renewcommand{\headrulewidth}{0.4pt}
    - \renewcommand{\footrulewidth}{0.4pt}
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    number_sections: yes
    toc: yes
  word_document:
    toc: yes
  html_document:
    number_sections: yes
    toc: yes
---

```{=html}
<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Best Practices}
-->
```
## Best practice publications using the OHDSI PatientLevelPrediction framework

+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Topic                 | Research Summary                                                                                                                     | Link                                                                                                                |
+=======================+======================================================================================================================================+=====================================================================================================================+
| Problem Specification | When is prediction suitable in observational data?                                                                                   | Guidelines needed                                                                                                   |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Data Creation         | Comparison of cohort vs case-control design                                                                                          | [Journal of Big Data](https://journalofbigdata.springeropen.com/articles/10.1186/s40537-021-00501-2)                |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Data Creation         | Addressing loss to follow-up (right censoring)                                                                                       | [BMC medical informatics and decision makingk](https://link.springer.com/article/10.1186/s12911-021-01408-x)        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Data Creation         | Investigating how to address left censoring in features construction                                                                 | [BMC Medical Research Methodology](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-021-01370-2) |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Data Creation         | Impact of over/under-sampling                                                                                                        | Paper under review                                                                                                  |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Data Creation         | Impact of phenotypes                                                                                                                 | Study Done - Paper submitted                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | How much data do we need for prediction - Learning curves at scale                                                                   | [International Journal of Medical Informatics](https://www.sciencedirect.com/science/article/pii/S1386505622000764) |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | What impact does test/train/validation design have on model performance                                                              | [BMJ Open](https://bmjopen.bmj.com/content/11/12/e050146)                                                           |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | What is the impact of the classifier                                                                                                 | [JAMIA](https://academic.oup.com/jamia/article/25/8/969/4989437?login=true)                                         |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | Can we find hyper-parameter combinations per classifier that consistently lead to good performing models when using claims/EHR data? | Study needs to be done                                                                                              |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | Can we use ensembles to combine different algorithm models within a database to improve models transportability?                     | Study Complete                                                                                                      |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Model development     | Can we use ensembles to combine models developed using different databases to improve models transportability?                       | [BMC Medical Informatics and Decision Making](https://link.springer.com/article/10.1186/s12911-022-01879-6)         |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Evaluation            | How should we present model performance? (e.g., new visualizations)                                                                  | [JAMIA Open](https://academic.oup.com/jamiaopen/article/4/1/ooab017/6168493?searchresult=1)                         |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Evaluation            | How to interpret external validation performance (can we figure out why the performance drops or stays consistent)?                  | Study needs to be done                                                                                              |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Evaluation            | Recalibration methods                                                                                                                | Study needs to be done                                                                                              |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| Evaluation            | Is there a way to automatically simplify models?                                                                                     | [Study protocol under development](https://ohdsi-studies.github.io/FeatureSelectionComparison/docs/Protocol.html)   |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
