\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction Framework},
            pdfauthor={Jenna Reps, Martijn J. Schuemie, Patrick B. Ryan, Peter R. Rijnbeek},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Implementing Existing Prediction Models using the OHDSI
PatientLevelPrediction Framework}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Jenna Reps, Martijn J. Schuemie, Patrick B. Ryan, Peter R. Rijnbeek}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2018-09-28}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead{}
\fancyhead[CO,CE]{Implementing Existing Prediction Models}
\fancyfoot[CO,CE]{PatientLevelPrediction Package Version 2.0.5}
\fancyfoot[LE,RO]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

This vignette describes how you can implement existing logistic
regression models in the Observational Health Data Sciences (OHDSI)
\href{http://www.github.com/OHDSI/PatientLevelPrediction}{\texttt{PatientLevelPrediction}}
framework. This allows you to for example externally validate them at
scale in the OHDSI data network.

As an example we are going to implement the CHADS2 model as described
in:

Gage BF, Waterman AD, Shannon W, Boechler M, Rich MW, Radford MJ.
Validation of clinical classification schemes for predicting stroke:
results from the National Registry of Atrial Fibrillation. JAMA. 2001
Jun 13;285(22):2864-70

To implement the model you need to create three tables: the model table,
the covariate table, and the intercept table. The model table specifies
the modelId (sequence number), the modelCovariateId (sequence number)
and the covariateValue (beta for the covariate). The covariate table
specifies the mapping between the covariates from the published model
and the standard covariates, i.e.~it maps to a combination of an
analysisid and a concept\_id (see below). The intercept table specifies
per modelId the intercept.

\section{Model implementation}\label{model-implementation}

\subsection{Define the model}\label{define-the-model}

The CHADS2 is a score based model with:

\begin{verbatim}
##   Points                        Covariate
## 1      1         Congestive heart failure
## 2      1                     Hypertension
## 3      1                  Age >= 75 years
## 4      1                Diabetes mellitus
## 5      2 Stroke/transient ischemic attack
\end{verbatim}

The model table should therefore be defined as:

\begin{verbatim}
##   modelId modelCovariateId covariateValue
## 1       1                1              1
## 2       1                2              1
## 3       1                3              1
## 4       1                4              1
## 5       1                5              2
\end{verbatim}

The covariateTable will then specify what standard covariates need to be
included in the model.

In this case we choose the following Standard SNOMED concept\_ids:
319835 for congestive heart failure, 316866 for hypertensive disorder,
201820 for diabetes, and 381591 for cerebrovascular disease. It is
allowed to add multiple concept\_ids as separate rows for the same
modelCovariateId if concept sets are needed. These concept\_ids can be
found using the vocabulary search in ATLAS.

The standard covariates are of the form: conceptid*1000 + analysisid.
The analysisid specifies the domain of the covariate and its lookback
window. Examples can be found here:
\url{https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecAnalyses.csv}

Our example of CHADS2 uses agegroup and conditions in the full history.
Therefore we need to define the standard covariates using the
FeatureExtraction::createCovariateSettings as follows:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(PatientLevelPrediction)}
\NormalTok{covSet <-}\StringTok{ }\NormalTok{FeatureExtraction}\OperatorTok{::}\KeywordTok{createCovariateSettings}\NormalTok{(}\DataTypeTok{useDemographicsAgeGroup =}\NormalTok{ T,                             }
                                                     \DataTypeTok{useConditionOccurrenceLongTerm =}\NormalTok{ T,}
                                                     \DataTypeTok{includedCovariateIds =} \OtherTok{NULL}\NormalTok{,}
                                                     \DataTypeTok{longTermStartDays =} \OperatorTok{-}\DecValTok{9999}\NormalTok{, }
                                                     \DataTypeTok{endDays =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

In the above code we used the useConditionOccurrenceLongTerm (these have
an analysis id of 102) and we defined the longTermStartDays to be -9999
days relative to index (so we get the full history). We include the
index date in our lookback period by specifying endDays = 0. The
includeCovariateIds is set to NULL here, but this will be updated
automatically later on. As we picked analysis id 102, the standard
covariate for anytime prior congestive heart failure is 319835102. The
same logic follows for the other conditions, so the covariate table will
be:

\begin{verbatim}
##   modelCovariateId covariateId
## 1                1   319835102
## 2                2   316866102
## 3                3       15003
## 4                3       16003
## 5                3       17003
## 6                3       18003
## 7                3       19003
## 8                4   201820102
## 9                5   381591102
\end{verbatim}

modelCovariateId 3 was age\textgreater{}= 75, as the standard covariate
age groups are in 5 year groups, we needed to add the age groups 75-80,
80-85, 85-90, 90-95 and 95-100, these correspond to the covaraiteIds
15003, 16003, 17003, 18003 and 19003 respectively.

To create the tables in R for CHADS2 you need to make the following
dataframes:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model_table <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{modelId =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                          \DataTypeTok{modelCovariateId =} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{, }
                          \DataTypeTok{coefficientValue =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{)}
\NormalTok{                          )}

\NormalTok{covariate_table <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{modelCovariateId =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{),}
                              \DataTypeTok{covariateId =} \KeywordTok{c}\NormalTok{(}\DecValTok{319835102}\NormalTok{, }\DecValTok{316866102}\NormalTok{, }
                                            \DecValTok{15003}\NormalTok{, }\DecValTok{16003}\NormalTok{, }\DecValTok{17003}\NormalTok{, }\DecValTok{18003}\NormalTok{, }\DecValTok{19003}\NormalTok{, }
                                            \DecValTok{201820102}\NormalTok{, }\DecValTok{381591102}\NormalTok{)}
\NormalTok{                              )}

\NormalTok{interceptTable <-}\StringTok{  }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{modelId =} \DecValTok{1}\NormalTok{, }
                              \DataTypeTok{interceptValue =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Create the model}\label{create-the-model}

Now you have everything in place to actually create the existing model.
First specify the current environment as executing
createExistingModelSql creates two functions for running the existing
model into the specified environment. You need to specify the type of
model (either logistic or score), in our example we are calculating a
score. We finally need to specify the analysisId for the newly created
CHADS2 covariate.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{e <-}\StringTok{ }\KeywordTok{environment}\NormalTok{()}
\NormalTok{PatientLevelPrediction}\OperatorTok{::}\KeywordTok{createExistingModelSql}\NormalTok{(}\DataTypeTok{modelTable =}\NormalTok{ model_table, }
                       \DataTypeTok{modelNames =} \StringTok{'CHADS2'}\NormalTok{, }
                       \DataTypeTok{interceptTable =} \KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{modelId =} \DecValTok{1}\NormalTok{, }\DataTypeTok{interceptValue =} \DecValTok{0}\NormalTok{),}
                       \DataTypeTok{covariateTable =}\NormalTok{ covariate_table, }
                       \DataTypeTok{type =} \StringTok{'score'}\NormalTok{,}
                       \DataTypeTok{analysisId =} \DecValTok{112}\NormalTok{, }\DataTypeTok{covariateSettings =}\NormalTok{ covSettings, }\DataTypeTok{e =}\NormalTok{ e)}
\end{Highlighting}
\end{Shaded}

Once run you will find two new functions in your environment:

\begin{itemize}
\tightlist
\item
  createExistingmodelsCovariateSettings()
\item
  getExistingmodelsCovariateSettings()
\end{itemize}

\subsection{Run the model}\label{run-the-model}

Now you can use the functions you previously created to extract the
existing model risk scores for a target population:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plpData <-}\StringTok{ }\NormalTok{PatientLevelPrediction}\OperatorTok{::}\KeywordTok{getPlpData}\NormalTok{(connectionDetails, }
                      \DataTypeTok{cdmDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{,}
                      \DataTypeTok{cohortId =} \DecValTok{1}\NormalTok{,}
                      \DataTypeTok{outcomeIds =} \DecValTok{2}\NormalTok{, }
                      \DataTypeTok{cohortDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{, }
                      \DataTypeTok{cohortTable =}  \StringTok{'cohort'}\NormalTok{ , }
                      \DataTypeTok{outcomeDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{, }
                      \DataTypeTok{outcomeTable =} \StringTok{'cohort'}\NormalTok{, }
                      \DataTypeTok{covariateSettings =}  \KeywordTok{createExistingmodelsCovariateSettings}\NormalTok{(),}
                      \DataTypeTok{sampleSize =} \DecValTok{20000}
\NormalTok{                      )}
\end{Highlighting}
\end{Shaded}

To implement and evaluate an existing model you can use the function:

\texttt{PatientLevelPrediction::evaluateExistingModel()}

with the following parameters:

\begin{itemize}
\tightlist
\item
  modelTable - a data.frame containing the columns: modelId, covariateId
  and coefficientValue
\item
  covariateTable - a data.frame containing the columns: covariateId and
  standardCovariateId - this provides a set of standardCovariateId to
  define each model covariate.
\item
  interceptTable - a data.frame containing the columns modelId and
  interceptValue or NULL if the model doesn't have an intercept (equal
  to zero).
\item
  type - the type of model (either: score or logistic)
\item
  covariateSettings - this is used to determine the startDay and endDay
  for the standard covariates
\item
  customCovariates - a data.frame with the covariateId and sql to
  generate the covariate value.
\item
  riskWindowStart - the time at risk starts at target cohort start date
  + riskWindowStart
\item
  addExposureDaysToEnd - if true then the time at risk window ends a the
  cohort end date + riskWindowEnd rather than cohort start date +
  riskWindowEnd
\item
  riskWindowEnd - the time at risk ends at target cohort start/end date
  + riskWindowStart
\item
  requireTimeAtRisk - whether to add a constraint to the number of days
  observed during the time at risk period in including people into the
  study
\item
  minTimeAtRisk - the minimum number of days observation during the time
  at risk a target population person needs to be included
\item
  includeAllOutcomes - Include outcomes even if they do not satisfy the
  minTimeAtRisk? (useful if the outcome is associated to death or rare)
\item
  removeSubjectsWithPriorOutcome - remove target population people who
  have the outcome prior to the time at tisk period?
\item
  connectionDetails - the connection to the CDM database
\end{itemize}

Finally you need to add the settings for downloading the new data:

\begin{itemize}
\tightlist
\item
  cdmDatabaseSchema
\item
  cohortDatabaseSchema
\item
  cohortTable
\item
  cohortId
\item
  outcomeDatabaseSchema
\item
  outcomeTable
\item
  outcomeId
\item
  oracleTempSchema
\end{itemize}

To run the external validation of an existing model where the target
population are those in the cohort table with id 1 and the outcome is
those in the cohort table with id 2 and we are looking to predict first
time occurrence of the outcome 1 day to 365 days after the target cohort
start date (assuming you have the modelTable, covariateTable and
interceptTable in the format explained above):

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# in our example the existing model uses gender and condition groups looking back 200 days:}
\NormalTok{covSet <-}\StringTok{ }\NormalTok{FeatureExtraction}\OperatorTok{::}\KeywordTok{createCovariateSettings}\NormalTok{(}\DataTypeTok{useDemographicsGender =}\NormalTok{ T,}
                                                     \DataTypeTok{useConditionGroupEraMediumTerm =}\NormalTok{ T, }
                                                     \DataTypeTok{mediumTermStartDays =} \OperatorTok{-}\DecValTok{200}\NormalTok{)}

\NormalTok{result <-}\StringTok{ }\KeywordTok{evaluateExistingModel}\NormalTok{(}\DataTypeTok{modelTable =}\NormalTok{ modelTable,}
                                \DataTypeTok{covariateTable =}\NormalTok{ covariateTable,}
                                \DataTypeTok{interceptTable =} \OtherTok{NULL}\NormalTok{,}
                                \DataTypeTok{type =} \StringTok{'score'}\NormalTok{, }
                                \DataTypeTok{covariateSettings =}\NormalTok{  covSet,}
                                \DataTypeTok{riskWindowStart =} \DecValTok{1}\NormalTok{, }
                                \DataTypeTok{addExposureDaysToEnd =}\NormalTok{ F, }
                                \DataTypeTok{riskWindowEnd =} \DecValTok{365}\NormalTok{, }
                                \DataTypeTok{requireTimeAtRisk =}\NormalTok{ T, }
                                \DataTypeTok{minTimeAtRisk =} \DecValTok{364}\NormalTok{, }
                                \DataTypeTok{includeAllOutcomes =}\NormalTok{ T, }
                                \DataTypeTok{removeSubjectsWithPriorOutcome =}\NormalTok{ T, }
                                \DataTypeTok{connectionDetails =}\NormalTok{ connectionDetails, }
                                \DataTypeTok{cdmDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{,}
                                \DataTypeTok{cohortId =} \DecValTok{1}\NormalTok{,}
                                \DataTypeTok{outcomeId =} \DecValTok{2}\NormalTok{, }
                                \DataTypeTok{cohortDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{, }
                                \DataTypeTok{cohortTable =}  \StringTok{'cohort'}\NormalTok{ , }
                                \DataTypeTok{outcomeDatabaseSchema =} \StringTok{'databasename.dbo'}\NormalTok{, }
                                \DataTypeTok{outcomeTable =} \StringTok{'cohort'}
\NormalTok{                      )}
\end{Highlighting}
\end{Shaded}

\texttt{Result} will contain the performance and the predictions made by
the model.

\section{Acknowledgments}\label{acknowledgments}

Considerable work has been dedicated to provide the
\texttt{PatientLevelPrediction} package.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{citation}\NormalTok{(}\StringTok{"PatientLevelPrediction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Jenna Reps, Martijn J. Schuemie, Marc A. Suchard, Patrick B.
##   Ryan and Peter R. Rijnbeek (2018). PatientLevelPrediction:
##   Package for patient level prediction using data in the OMOP
##   Common Data Model. R package version 2.0.5.
## 
## A BibTeX entry for LaTeX users is
## 
##   @Manual{,
##     title = {PatientLevelPrediction: Package for patient level prediction using data in the OMOP Common Data
## Model},
##     author = {Jenna Reps and Martijn J. Schuemie and Marc A. Suchard and Patrick B. Ryan and Peter R. Rijnbeek},
##     year = {2018},
##     note = {R package version 2.0.5},
##   }
\end{verbatim}

\textbf{Please reference this paper if you use the PLP Package in your
work:}

\href{http://dx.doi.org/10.1093/jamia/ocy032}{Reps JM, Schuemie MJ,
Suchard MA, Ryan PB, Rijnbeek PR. Design and implementation of a
standardized framework to generate and evaluate patient-level prediction
models using observational healthcare data. J Am Med Inform Assoc.
2018;25(8):969-975.}

This work is supported in part through the National Science Foundation
grant IIS 1251151.


\end{document}
