<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction framework • PatientLevelPrediction</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction framework">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">PatientLevelPrediction</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/PatientLevelPrediction.html">Get started</a>
</li>
<li>
  <a href="../articles/Videos.html">Videos</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/AddingCustomAlgorithms.html">Adding Custom Patient-Level Prediction Algorithms</a>
    </li>
    <li>
      <a href="../articles/AddingExistingModels.html">Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction framework</a>
    </li>
    <li>
      <a href="../articles/BuildingDeepLearningModels.html">Building Deep Learning Models</a>
    </li>
    <li>
      <a href="../articles/BuildingEnsembleModels.html">Building Ensemble Models</a>
    </li>
    <li>
      <a href="../articles/BuildingMultiplePredictiveModels.html">Automatically Build Multiple Patient-Level Predictive Models</a>
    </li>
    <li>
      <a href="../articles/BuildingPredictiveModels.html">Building patient-level predictive models</a>
    </li>
    <li>
      <a href="../articles/CreatingNetworkStudies.html">Making  patient-level predictive network study packages</a>
    </li>
    <li>
      <a href="../articles/CustomPredictionAlgorithms.html">Custom patient-level prediction algorithms</a>
    </li>
    <li>
      <a href="../articles/GeneratingLearningCurves.html">Generating Learning Curves</a>
    </li>
    <li>
      <a href="../articles/ImplementingExistingModels.html">Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction Framework</a>
    </li>
    <li>
      <a href="../articles/InstallationGuide.html">Patient-Level Prediction Installation Guide</a>
    </li>
    <li>
      <a href="../articles/PlottingLearningCurves.html">Plotting learning curves</a>
    </li>
    <li>
      <a href="../articles/Videos.html">Demo Videos</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/OHDSI/PatientLevelPrediction">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Implementing Existing Prediction Models using the OHDSI PatientLevelPrediction framework</h1>
                        <h4 class="author">Jenna Reps, Martijn J. Schuemie, Patrick B. Ryan, Peter R. Rijnbeek</h4>
            
            <h4 class="date">2019-03-04</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/OHDSI/PatientLevelPrediction/blob/master/vignettes/AddingExistingModels.Rmd"><code>vignettes/AddingExistingModels.Rmd</code></a></small>
      <div class="hidden name"><code>AddingExistingModels.Rmd</code></div>

    </div>

    
    
<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Adding existing patient-level predictive models}
-->

<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>This vignette describes how you can implement existing logistic regression models in the <code>PatientLevelPrediction</code> framework. This allows you to for example externally validate them at scale in the OHDSI data network.</p>
<p>As an example we are going to implement the CHADS2 model:</p>
<p>Gage BF, Waterman AD, Shannon W, Boechler M, Rich MW, Radford MJ. Validation of clinical classification schemes for predicting stroke: results from the National Registry of Atrial Fibrillation. JAMA. 2001 Jun 13;285(22):2864-70</p>
<p>To implement the model you need to create three tables: the model table, the covariate table, and the intercept table. The model table specifies the modelId (sequence number), the modelCovariateId (sequence number) and the covariateValue (beta for the covariate). The covariate table specifies the mapping between the covariates from the published model and the standard Patient Level Prediction framework covariates, i.e. its maps to a combination of an analysisid and a concept_id (see below). The intercept table specifies per modelId the intercept.</p>
</div>
<div id="model-implementation" class="section level1">
<h1 class="hasAnchor">
<a href="#model-implementation" class="anchor"></a>Model implementation</h1>
<div id="define-the-model" class="section level2">
<h2 class="hasAnchor">
<a href="#define-the-model" class="anchor"></a>Define the model</h2>
<p>The CHADS2 is a score based model with:</p>
<pre><code>##   Points                        Covariate
## 1      1         Congestive heart failure
## 2      1                     Hypertension
## 3      1                  Age &gt;= 75 years
## 4      1                Diabetes mellitus
## 5      2 Stroke/transient ischemic attack</code></pre>
<p>The model table should therefore be defined as:</p>
<pre><code>##   modelId modelCovariateId covariateValue
## 1       1                1              1
## 2       1                2              1
## 3       1                3              1
## 4       1                4              1
## 5       1                5              2</code></pre>
<p>The covariateTable will then specify what standard covariates need to be included in the model.</p>
<p>In this case we choose the following Standard SNOMED concept_ids: 319835 for congestive heart failure, 316866 for hypertensive disorder, 201820 for diabetes, and 381591 for cerebrovascular disease. It is allowed to add multiple concept_ids as seperate rows for the same modelCovariateId if concept sets are needed. These concept_ids can be found using the vocabulary search in ATLAS.</p>
<p>The Patient Level Prediction standard covariates are of the form: conceptid*1000 + analysisid. The analysisid specifies the domain of the covariate and its lookback window. Examples can be found here: <a href="https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecAnalyses.csv" class="uri">https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecAnalyses.csv</a></p>
<p>Our example of CHADS2 uses agegroup and conditions in the full history. Therefore we need to define the standard covariates using the FeatureExtraction::createCovariateSettings as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(PatientLevelPrediction)
covSet &lt;-<span class="st"> </span>FeatureExtraction<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/FeatureExtraction/topics/createCovariateSettings">createCovariateSettings</a></span>(<span class="dt">useDemographicsAgeGroup =</span> T,                             
                                                     <span class="dt">useConditionOccurrenceLongTerm =</span> T,
                                                     <span class="dt">includedCovariateIds =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(),
                                                     <span class="dt">longTermStartDays =</span> <span class="op">-</span><span class="dv">9999</span>, 
                                                     <span class="dt">endDays =</span> <span class="dv">0</span>)</code></pre></div>
<p>In the above code we used the useConditionOccurrenceLongTerm (these have an analysis id of 102) and we defined the longTermStartDays to be -9999 days relative to index (so we get the full history). We include the index date in our lookback period by specifying endDays = 0. The includeCovariateIds is set to 0, but this will be updated when you run the next code to pick out the standard covariates of interest. As we picked analysis id 102, the standard covariate for anytime prior congestive heart failure is 319835102, the same logic follows for the other conditions, so the covariate table will be:</p>
<pre><code>##   modelCovariateId covariateId
## 1                1   319835102
## 2                2   316866102
## 3                3       15003
## 4                3       16003
## 5                3       17003
## 6                3       18003
## 7                3       19003
## 8                4   201820102
## 9                5   381591102</code></pre>
<p>modelCovariateId 3 was age&gt;= 75, as the standard covariate age groups are in 5 year groups, we needed to add the age groups 75-80, 80-85, 85-90, 90-95 and 95-100, these correspond to the covaraiteIds 15003, 16003, 17003, 18003 and 19003 respectively.</p>
<p>To create the tables in R for CHADS2 you need to make the following dataframes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_table &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">modelId =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),
                          <span class="dt">modelCovariateId =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, 
                          <span class="dt">coefficientValue =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>)
                          )

covariate_table &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">modelCovariateId =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>),
                              <span class="dt">covariateId =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">319835102</span>, <span class="dv">316866102</span>, 
                                            <span class="dv">15003</span>, <span class="dv">16003</span>, <span class="dv">17003</span>, <span class="dv">18003</span>, <span class="dv">19003</span>, 
                                            <span class="dv">201820102</span>, <span class="dv">381591102</span>)
                              )

interceptTable &lt;-<span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">modelId =</span> <span class="dv">1</span>, 
                              <span class="dt">interceptValue =</span> <span class="dv">0</span>)</code></pre></div>
</div>
<div id="create-the-model" class="section level2">
<h2 class="hasAnchor">
<a href="#create-the-model" class="anchor"></a>Create the model</h2>
<p>Now you have everything in place actually create the existing model. First specify the current environment as executing createExistingModelSql creates two functions for running the existing model into the specificed environment. Next a few additional settings are needed: as some models require an intercept, there is an option for this (set it to 0 if an intercept isn’t needed), also the type specifies the final mapping (either logistic or linear/score), in our example we are calculating a score. We finally need to specify the analysisId for the newly created CHADS2 covariate.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">e &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/environment">environment</a></span>()
PatientLevelPrediction<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/PatientLevelPrediction/topics/createExistingModelSql">createExistingModelSql</a></span>(<span class="dt">modelTable =</span> model_table, 
                       <span class="dt">modelNames =</span> <span class="st">'CHADS2'</span>, 
                       <span class="dt">interceptTable =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">modelId =</span> <span class="dv">1</span>, <span class="dt">interceptValue =</span> <span class="dv">0</span>),
                       <span class="dt">covariateTable =</span> covariate_table, 
                       <span class="dt">type =</span> <span class="st">'score'</span>,
                       <span class="dt">analysisId =</span> <span class="dv">112</span>, <span class="dt">covariateSettings =</span> covSettings, <span class="dt">e =</span> e)</code></pre></div>
<p>Once run you will find two new functions in your environment:</p>
<ul>
<li>createExistingmodelsCovariateSettings()</li>
<li>getExistingmodelsCovariateSettings()</li>
</ul>
</div>
</div>
<div id="run-the-model" class="section level1">
<h1 class="hasAnchor">
<a href="#run-the-model" class="anchor"></a>Run the model</h1>
<p>Now you can use the functions you previously created to extract the existing model risk scores for a target population:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpData &lt;-<span class="st"> </span>PatientLevelPrediction<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/PatientLevelPrediction/topics/getPlpData">getPlpData</a></span>(connectionDetails, 
                      <span class="dt">cdmDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>,
                      <span class="dt">cohortId =</span> <span class="dv">1</span>,
                      <span class="dt">outcomeIds =</span> <span class="dv">2</span>, 
                      <span class="dt">cohortDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>, 
                      <span class="dt">cohortTable =</span>  <span class="st">'cohort'</span> , 
                      <span class="dt">outcomeDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>, 
                      <span class="dt">outcomeTable =</span> <span class="st">'cohort'</span>, 
                      <span class="dt">covariateSettings =</span>  <span class="kw">createExistingmodelsCovariateSettings</span>(),
                      <span class="dt">sampleSize =</span> <span class="dv">20000</span>
                      )</code></pre></div>
<p>To implement and evaluate an existing model you can use the function:</p>
<p><code><a href="../reference/evaluateExistingModel.html">PatientLevelPrediction::evaluateExistingModel()</a></code></p>
<p>with the following parameters:</p>
<ul>
<li>modelTable - a data.frame containing the columns: modelId, covariateId and coefficientValue</li>
<li>covariateTable - a data.frame containing the columns: covariateId and standardCovariateId - this provides a set of standardCovariateId to define each model covariate.</li>
<li>interceptTable - a data.frame containing the columns modelId and interceptValue or NULL if the model doesn’t have an intercept (equal to zero).</li>
<li>type - the type of model (either: score or logistic)</li>
<li>covariateSettings - this is used to determine the startDay and endDay for the standard covariates</li>
<li>customCovariates - a data.frame with the covariateId and sql to generate the covariate value.</li>
<li>riskWindowStart - the time at risk starts at target cohort start date + riskWindowStart</li>
<li>addExposureDaysToEnd - if true then the time at risk window ends a the cohort end date + riskWindowEnd rather than cohort start date + riskWindowEnd</li>
<li>riskWindowEnd - the time at risk ends at target cohort start/end date + riskWindowStart</li>
<li>requireTimeAtRisk - whether to add a constraint to the number of days observed during the time at risk period in including people into the study</li>
<li>minTimeAtRisk - the minimum number of days observation during the time at risk a target population person needs to be included</li>
<li>includeAllOutcomes - Include outcomes even if they do not satisfy the minTimeAtRisk? (useful if the outcome is associated to death or rare)</li>
<li>removeSubjectsWithPriorOutcome - remove target population people who have the outcome prior to the time at tisk period?</li>
<li>connectionDetails - the connection to the CDM database</li>
</ul>
<p>Finally you need to add the settings for downloading the new data:</p>
<ul>
<li>cdmDatabaseSchema</li>
<li>cohortDatabaseSchema</li>
<li>cohortTable</li>
<li>cohortId</li>
<li>outcomeDatabaseSchema</li>
<li>outcomeTable</li>
<li>outcomeId</li>
<li>oracleTempSchema</li>
</ul>
<p>To run the external validation of an existing model where the target population are those in the cohort table with id 1 and the outcome is those in the cohort table with id 2 and we are looking to predict first time occurrance of the outcome 1 day to 365 days after the target cohort start date (asusming you have the modelTable, covariateTable and interceptTable in the format explained above):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># if the existing model uses gender and condition groups looking back 200 days:</span>
covSet &lt;-<span class="st"> </span>FeatureExtraction<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/FeatureExtraction/topics/createCovariateSettings">createCovariateSettings</a></span>(<span class="dt">useDemographicsGender =</span> T,
                                                     <span class="dt">useConditionGroupEraMediumTerm =</span> T, 
                                                     <span class="dt">mediumTermStartDays =</span> <span class="op">-</span><span class="dv">200</span>)
result &lt;-<span class="st"> </span><span class="kw"><a href="../reference/evaluateExistingModel.html">evaluateExistingModel</a></span>(<span class="dt">modelTable =</span> modelTable,
                                <span class="dt">covariateTable =</span> covariateTable,
                                <span class="dt">interceptTable =</span> <span class="ot">NULL</span>,
                                <span class="dt">type =</span> <span class="st">'score'</span>, 
                                <span class="dt">covariateSettings =</span>  covSet,
                                <span class="dt">riskWindowStart =</span> <span class="dv">1</span>, 
                                <span class="dt">addExposureDaysToEnd =</span> F, 
                                <span class="dt">riskWindowEnd =</span> <span class="dv">365</span>, 
                                <span class="dt">requireTimeAtRisk =</span> T, 
                                <span class="dt">minTimeAtRisk =</span> <span class="dv">364</span>, 
                                <span class="dt">includeAllOutcomes =</span> T, 
                                <span class="dt">removeSubjectsWithPriorOutcome =</span> T, 
                                <span class="dt">connectionDetails =</span> connectionDetails, 
                                <span class="dt">cdmDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>,
                                <span class="dt">cohortId =</span> <span class="dv">1</span>,
                                <span class="dt">outcomeId =</span> <span class="dv">2</span>, 
                                <span class="dt">cohortDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>, 
                                <span class="dt">cohortTable =</span>  <span class="st">'cohort'</span> , 
                                <span class="dt">outcomeDatabaseSchema =</span> <span class="st">'databasename.dbo'</span>, 
                                <span class="dt">outcomeTable =</span> <span class="st">'cohort'</span>
                      )</code></pre></div>
</div>
<div id="acknowledgments" class="section level1">
<h1 class="hasAnchor">
<a href="#acknowledgments" class="anchor"></a>Acknowledgments</h1>
<p>Considerable work has been dedicated to provide the <code>PatientLevelPrediction</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/citation">citation</a></span>(<span class="st">"PatientLevelPrediction"</span>)</code></pre></div>
<pre><code>## 
## To cite PatientLevelPrediction in publications use:
## 
## Reps JM, Schuemie MJ, Suchard MA, Ryan PB, Rijnbeek P (2018).
## "Design and implementation of a standardized framework to generate
## and evaluate patient-level prediction models using observational
## healthcare data." _Journal of the American Medical Informatics
## Association_, *25*(8), 969-975. &lt;URL:
## https://doi.org/10.1093/jamia/ocy032&gt;.
## 
## A BibTeX entry for LaTeX users is
## 
##   @Article{,
##     author = {J. M. Reps and M. J. Schuemie and M. A. Suchard and P. B. Ryan and P. Rijnbeek},
##     title = {Design and implementation of a standardized framework to generate and evaluate patient-level prediction models using observational healthcare data},
##     journal = {Journal of the American Medical Informatics Association},
##     volume = {25},
##     number = {8},
##     pages = {969-975},
##     year = {2018},
##     url = {https://doi.org/10.1093/jamia/ocy032},
##   }</code></pre>
<p>This work is supported in part through the National Science Foundation grant IIS 1251151.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li>
<a href="#model-implementation">Model implementation</a><ul class="nav nav-pills nav-stacked">
<li><a href="#define-the-model">Define the model</a></li>
      <li><a href="#create-the-model">Create the model</a></li>
      </ul>
</li>
      <li><a href="#run-the-model">Run the model</a></li>
      <li><a href="#acknowledgments">Acknowledgments</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Jenna Reps, Martijn Schuemie, Marc Suchard, Patrick Ryan, Peter Rijnbeek.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
