# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aucWithCi <- function(propensityScores, treatment) {
    .Call('_PatientLevelPrediction_aucWithCi', PACKAGE = 'PatientLevelPrediction', propensityScores, treatment)
}

aucWithoutCi <- function(propensityScores, treatment) {
    .Call('_PatientLevelPrediction_aucWithoutCi', PACKAGE = 'PatientLevelPrediction', propensityScores, treatment)
}

bySum <- function(ffValues, ffBins) {
    .Call('_PatientLevelPrediction_bySum', PACKAGE = 'PatientLevelPrediction', ffValues, ffBins)
}

byMax <- function(ffValues, ffBins) {
    .Call('_PatientLevelPrediction_byMax', PACKAGE = 'PatientLevelPrediction', ffValues, ffBins)
}

