# @file PackageMaintenance
#
# Copyright 2019 Observational Health Data Sciences and Informatics
#
# This file is part of PatientLevelPrediction
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# recreate the html index when new documentation
pkgdown::build_site()

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("PatientLevelPrediction")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual and vignettes
system("rm extras/PatientLevelPrediction.pdf")
system("R CMD Rd2pdf ./ --output=extras/PatientLevelPrediction.pdf")

rmarkdown::render("vignettes/BuildingPredictiveModels.Rmd",
                  output_file = "../inst/doc/BuildingPredictiveModels.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE, toc_depth = 3,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/BuildingMultiplePredictiveModels.Rmd",
                  output_file = "../inst/doc/BuildingMultiplePredictiveModels.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/ImplementingExistingModels.Rmd",
                  output_file = "../inst/doc/ImplementingExistingModels.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/CreatingNetworkstudies.Rmd",
                  output_file = "../inst/doc/CreatingNetworkstudies.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/AddingCustomAlgorithms.Rmd",
                  output_file = "../inst/doc/AddingCustomAlgorithms.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/InstallationGuide.Rmd",
                  output_file = "../inst/doc/InstallationGuide.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/BuildingEnsembleModels.Rmd",
                  output_file = "../inst/doc/BuildingEnsembleModels.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/BuildingDeepLearningModels.Rmd",
                  output_file = "../inst/doc/BuildingDeepLearningModels.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/GeneratingLearningCurves.Rmd",
                  output_file = "../inst/doc/GeneratingLearningCurves.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

# automatically creating create arg functions for json Create arg functions:
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- OhdsiRTools::createArgFunction("getPlpData",
                                        excludeArgs = c("connectionDetails",
                                                        "cdmDatabaseSchema",
                                                        "oracleTempSchema",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "outcomeDatabaseSchema",
                                                        "outcomeTable",
                                                        "cdmVersion",
                                                        "cohortId",
                                                        "outcomeIds"),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("createStudyPopulation",
                                        excludeArgs = c("plpData", "population", "outcomeId"),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setModel", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setAdaBoost", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setDecisionTree", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setGradientBoostingMachine",
                                        excludeArgs = c(),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setKNN", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setLassoLogisticRegression",
                                        excludeArgs = c(),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setMLP", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setNaiveBayes", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("setRandomForest", excludeArgs = c(), rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("runPlp",
                                        excludeArgs = c("population", "plpData", "modelSettings"),
                                        rCode = rCode)

writeLines(rCode, "r/CreateArgFunctions.R")
OhdsiRTools::formatRFile("r/CreateArgFunctions.R")
